# Generated by Django 6.0 on 2026-02-23 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_medicalrecord_doctor_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment_plan',
            field=models.TextField(),
        ),
    ]
