# Generated by Django 6.0 on 2026-02-27 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_role_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('status', models.TextField(choices=[('stable', 'Stable'), ('improving', 'Improving'), ('critical', 'Critical'), ('recovered', 'Recovered')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicalrecord')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_progresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
