# Generated by Django 6.0 on 2026-02-27 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_treatmentprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentprogress',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
