# Generated by Django 6.0 on 2026-02-27 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_treatmentprogress_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentprogress',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='app.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='treatmentprogress',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
